In [20]:
import cv2
import numpy as np


In [3]:
import matplotlib

In [163]:
img = cv2.imread("/Users/romanisaev/Desktop/data xmashack/example_3.png", cv2.IMREAD_UNCHANGED)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


In [22]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
array.shape

(3, 3)

In [ ]:
def calc

In [35]:
c = array.max() - array.min()
nu = (array.max() + array.min())/2
c_star = 4
Ic = 3
first_cond, second_cond = np.logical_and(array >= nu, c < c_star), np.logical_and(array >= Ic, c >= c_star)
mask_M = np.logical_or(first_cond, second_cond)
mask_M



array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
def calc_bernsen_mask(array, c_star, Ic):
    c = array.max() - array.min()
    nu = (array.max() + array.min())/2
    print(f'c: {c}, nu: {nu}')
    first_cond, second_cond = np.logical_and(array >= nu, c < c_star), np.logical_and(array >= Ic, c >= c_star)
    mask_M = np.logical_or(first_cond, second_cond)
    return mask_M

def calc_bernsen_pixel(array, i, j, c_star, Ic):
    c = array.max() - array.min()
    #nu = array.mean()
    nu = (array.max() + array.min())/2
    if (array[i][i] >= nu and c < c_star) or (c >= c_star and array[i][i] >= Ic):
        return 1
    else:
        return 0

In [114]:
def save_mask_png(array, name):
    imgRow=np.size(array, 0)
    imgCol=np.size(array, 1)
    rgbMask = np.zeros([imgRow, imgCol, 3], dtype = np.int64)
    rgbMask[:,:,0] = rgbMask[:,:,1] = rgbMask[:,:,2] = array*255
    cv2.imwrite(f'{name}.png', rgbMask)
    

In [115]:
def calc_N_mask(array):
    return array > (array.max()*0.99)


In [164]:
from matplotlib import pyplot as plt
import cv2

img = cv2.imread("/Users/romanisaev/Desktop/data xmashack/example_3.png", cv2.IMREAD_UNCHANGED)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)



In [55]:
np.size(img, 0)


2234

In [165]:
mask1 = calc_bernsen_mask(gray, 220, 240)
mask2 = calc_N_mask(gray)
save_mask_png(mask1, 'M')
save_mask_png(mask2, 'N')

c: 255, nu: 127.5


In [170]:
mask1

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [169]:
np.where(mask1==True, 1, img[:,:,0])

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [60, 60, 60, ..., 49, 49, 49],
       [60, 60, 60, ..., 49, 49, 49],
       [60, 60, 60, ..., 49, 49, 49]], dtype=uint16)

In [171]:
imgRow=np.size(mask1, 0)
imgCol=np.size(mask1, 1)
rgbMask = np.zeros([imgRow, imgCol, 3], dtype = np.int64)
rgbMask[:,:, 1] = np.where(mask1==True, 0, img[:,:,1])
rgbMask[:,:, 2] = np.where(mask1==True, 0, img[:,:,2])
rgbMask[:,:, 0] = np.where(mask1==True, 255, img[:,:,0])



cv2.imwrite(f'colored_M.png', rgbMask)

True

In [157]:
(rgbMask[:,:,0] == 1).sum()

173382

In [122]:
(numLabels, labels, stats, centroids) = cv2.connectedComponentsWithStats(np.logical_or(mask1, mask2).astype(np.int8), connectivity=8)

In [123]:
mask3 = (labels >= 1).astype(np.int8)
save_mask_png(mask3, 'P')

In [149]:
def get_R_mask(rgb_img, C):
    b,g,r = rgb_img[:,:,0], rgb_img[:,:,1], rgb_img[:,:,2]
    first = (np.abs(r-g) + np.abs(g-b) + np.abs(b-r)) < C
    second = np.logical_or(np.logical_or(r > 0.8*r.max(), g > 0.8*g.max()), b > 0.8*b.max())
    return np.logical_and(first, second)
    

In [150]:
mask4 = get_R_mask(img, 0.000001)
print(mask4.sum())
save_mask_png(mask4, 'R')


522055


In [147]:
mask4

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [112]:
imgRow=np.size(img, 0)
imgCol=np.size(img, 1)
print("imgRow:%d, imgCol:%d" % (imgRow, imgCol))
print("shape:", img.shape)

rgbMask = np.zeros([imgRow, imgCol, 3], dtype = np.int64)
rgbMask[:,:,0] = rgbMask[:,:,1] = rgbMask[:,:,2] = mask3*255
cv2.imwrite('py_sh_out_01.png', rgbMask)



imgRow:2234, imgCol:3456
shape: (2234, 3456, 4)


True